### ISSUE TITLE
Loading .css/.js broken

### ISSUE THREAD

**Issue by silug** [binford2k/showoff#918]
With a file `all.css` in the root directory, current master fails to load the file with the following error:

```
 Invalid object all.css requested.
 undefined method `all.css' for #<Showoff:0x0000560264113e30>
```

I get a similar failure with *.js.

The error seems to have been introduced in b74f333.
